apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-v3
  template:
    metadata:
      labels:
        app: my-app-v3
    spec:
      containers:
      - name: my-app-v3
        image: abmateenmax5657/docker-ci-demo:latest
        ports:
        - containerPort: 3000

